<h1>Linear Regression Model for predicting Life Expectancy.</h1>

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

<h1>Loading the Data.</h1>

In [4]:
df= pd.read_csv('https://docs.google.com/spreadsheets/d/1PZyB7ce2W79PC-AgTuXwd8xW0zWwtk6Jqd8Qia2nxPE/export?format=csv')
df.head()

Country  Year     Status  Life expectancy  Adult Mortality  \
0  Australia  2015  Developed             82.8             59.0   
1  Australia  2014  Developed             82.7              6.0   
2  Australia  2013  Developed             82.5             61.0   
3  Australia  2012  Developed             82.3             61.0   
4  Australia  2011  Developed             82.0             63.0   

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles  ...  \
0              1      NaN                 0.00000         93.0       74  ...   
1              1     9.71             10769.36305         91.0      340  ...   
2              1     9.87             11734.85381         91.0      158  ...   
3              1    10.03             11714.99858         91.0      199  ...   
4              1    10.30             10986.26527         92.0      190  ...   

   Polio  Total expenditure  Diphtheria  HIV/AIDS          GDP  Population  \
0   93.0                NaN        93.0       0.1  56554.38760  23789338.0   
1   92.0               9.42        92.0       0.1  62214.69120   2346694.0   
2   91.0               9.36        91.0       0.1  67792.33860  23117353.0   
3   92.0               9.36        92.0       0.1  67677.63477  22728254.0   
4   92.0               9.20        92.0       0.1  62245.12900    223424.0   

   thinness  1-19 years  thinness 5-9 years  Income composition of resources  \
0                   0.6                 0.6                            0.937   
1                   0.6                 0.6                            0.936   
2                   0.6                 0.6                            0.933   
3                   0.6                 0.6                            0.930   
4                   0.6                 0.6                            0.927   

   Schooling  
0       20.4  
1       20.4  
2       20.3  
3       20.1  
4       19.8  

[5 rows x 22 columns]

<h1>Processing the Data.</h1>

In [7]:
df=df.dropna()


In [9]:
df.loc[df["Status"] == "Developed", "Status"] = 1
df.loc[df["Status"] == "Developing", "Status"] = 0

In [11]:
y_df=df['Life expectancy']
y_df_numpy=y_df.to_numpy()
y_df_numpy

array([82.7, 82.5, 82.3, ..., 44.8, 45.3, 46. ])

In [13]:
df_X=df.drop(columns=['Life expectancy'])
df_X

Country  Year Status  Adult Mortality  infant deaths  Alcohol  \
1     Australia  2014      1              6.0              1     9.71   
2     Australia  2013      1             61.0              1     9.87   
3     Australia  2012      1             61.0              1    10.03   
4     Australia  2011      1             63.0              1    10.30   
5     Australia  2010      1             64.0              1    10.52   
...         ...   ...    ...              ...            ...      ...   
2933   Zimbabwe  2004      0            723.0             27     4.36   
2934   Zimbabwe  2003      0            715.0             26     4.06   
2935   Zimbabwe  2002      0             73.0             25     4.43   
2936   Zimbabwe  2001      0            686.0             25     1.72   
2937   Zimbabwe  2000      0            665.0             24     1.68   

      percentage expenditure  Hepatitis B  Measles   BMI  ...  Polio  \
1               10769.363050         91.0      340  66.1  ...   92.0   
2               11734.853810         91.0      158  65.5  ...   91.0   
3               11714.998580         91.0      199  65.0  ...   92.0   
4               10986.265270         92.0      190  64.4  ...   92.0   
5                8875.786493         92.0       70  63.9  ...   92.0   
...                      ...          ...      ...   ...  ...    ...   
2933                0.000000         68.0       31  27.1  ...   67.0   
2934                0.000000          7.0      998  26.7  ...    7.0   
2935                0.000000         73.0      304  26.3  ...   73.0   
2936                0.000000         76.0      529  25.9  ...   76.0   
2937                0.000000         79.0     1483  25.5  ...   78.0   

      Total expenditure  Diphtheria  HIV/AIDS           GDP  Population  \
1                  9.42        92.0       0.1  62214.691200   2346694.0   
2                  9.36        91.0       0.1  67792.338600  23117353.0   
3                  9.36        92.0       0.1  67677.634770  22728254.0   
4                  9.20        92.0       0.1  62245.129000    223424.0   
5                  9.20        92.0       0.1  51874.848000    223175.0   
...                 ...         ...       ...           ...         ...   
2933               7.13        65.0      33.6    454.366654  12777511.0   
2934               6.52        68.0      36.7    453.351155  12633897.0   
2935               6.53        71.0      39.8     57.348340    125525.0   
2936               6.16        75.0      42.1    548.587312  12366165.0   
2937               7.10        78.0      43.5    547.358878  12222251.0   

      thinness  1-19 years  thinness 5-9 years  \
1                      0.6                 0.6   
2                      0.6                 0.6   
3                      0.6                 0.6   
4                      0.6                 0.6   
5                      0.7                 0.6   
...                    ...                 ...   
2933                   9.4                 9.4   
2934                   9.8                 9.9   
2935                   1.2                 1.3   
2936                   1.6                 1.7   
2937                  11.0                11.2   

      Income composition of resources  Schooling  
1                               0.936       20.4  
2                               0.933       20.3  
3                               0.930       20.1  
4                               0.927       19.8  
5                               0.927       19.5  
...                               ...        ...  
2933                            0.407        9.2  
2934                            0.418        9.5  
2935                            0.427       10.0  
2936                            0.427        9.8  
2937                            0.434        9.8  

[1649 rows x 21 columns]

In [15]:
df_X_one_hot_applied=pd.get_dummies(df_X,columns=['Country'])
df_X_one_hot_applied=df_X_one_hot_applied.astype(int)
#at this step, we must normalize the data.
scaler = StandardScaler()

# Fit and transform the feature data
X_df_numpy = scaler.fit_transform(df_X_one_hot_applied)
# X_df_numpy=df_X_one_hot_applied.to_numpy()
# X_df_numpy=df_X.to_numpy()
X_df_numpy

                                      

array([[ 1.5072885 ,  2.41123404, -1.29490025, ..., -0.09581193,
        -0.0781107 , -0.09581193],
       [ 1.26257858,  2.41123404, -0.85585707, ..., -0.09581193,
        -0.0781107 , -0.09581193],
       [ 1.01786865,  2.41123404, -0.85585707, ..., -0.09581193,
        -0.0781107 , -0.09581193],
       ...,
       [-1.42923064, -0.4147254 , -0.76006583, ..., -0.09581193,
        -0.0781107 , 10.43711327],
       [-1.67394057, -0.4147254 ,  4.13327002, ..., -0.09581193,
        -0.0781107 , 10.43711327],
       [-1.91865049, -0.4147254 ,  3.96563535, ..., -0.09581193,
        -0.0781107 , 10.43711327]])

In [17]:
X_df_numpy.shape

(1649, 153)

In [19]:
y_df_numpy.shape

(1649,)

In [21]:
ones_column = np.ones((X_df_numpy.shape[0], 1))

In [23]:
X_df_numpy = np.hstack((X_df_numpy, ones_column))

In [25]:
X_df_numpy

array([[ 1.5072885 ,  2.41123404, -1.29490025, ..., -0.0781107 ,
        -0.09581193,  1.        ],
       [ 1.26257858,  2.41123404, -0.85585707, ..., -0.0781107 ,
        -0.09581193,  1.        ],
       [ 1.01786865,  2.41123404, -0.85585707, ..., -0.0781107 ,
        -0.09581193,  1.        ],
       ...,
       [-1.42923064, -0.4147254 , -0.76006583, ..., -0.0781107 ,
        10.43711327,  1.        ],
       [-1.67394057, -0.4147254 ,  4.13327002, ..., -0.0781107 ,
        10.43711327,  1.        ],
       [-1.91865049, -0.4147254 ,  3.96563535, ..., -0.0781107 ,
        10.43711327,  1.        ]])

<h1>Now we have converted both our Xs and ys into numpy arrays.</h1>

In [30]:
def calculate_cost(y_actual,y_predicted):
    num=y_actual.shape[0]
    cost=(1/(2*num))*np.sum(np.square(y_actual-y_predicted))
    return cost

In [32]:
def hypothesis(X,theta):
    y_predicted=np.dot(X,theta)
    return y_predicted

<h1>Applying Gradient Descent.</h1>

In [34]:
def gradient_descent(X,y_actual,alpha,num_iterations):
    num=y_actual.shape[0]
    theta=np.zeros(X.shape[1])
    
    for i in range(num_iterations):
        predictions=hypothesis(X,theta)
        error=predictions-y_actual
        gradient=(1/num)*np.dot(X.T,error)
        theta-=alpha*gradient

    return calculate_cost(y_actual,hypothesis(X,theta))
        

<h2>Calculating the accuracy.</h2>

In [39]:
mse=gradient_descent(X_df_numpy,y_df_numpy,0.01,10000)
np.sqrt(mse)
print("The Mean Square Error is: ",mse)

The Mean Square Error is:  1.2677097655143046
